// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldCup.Infrastructure;

#nullable disable

namespace WorldCup.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorldCup.Domain.Entities.GroupQualifierBet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("PontosObtidos")
                        .HasColumnType("int");

                    b.Property<int>("PrimeiroTeamId")
                        .HasColumnType("int");

                    b.Property<int>("SegundoTeamId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrimeiroTeamId");

                    b.HasIndex("SegundoTeamId");

                    b.HasIndex("UserId", "Grupo")
                        .IsUnique();

                    b.ToTable("GroupQualifierBets");
                });

            modelBuilder.Entity("WorldCup.Domain.Entities.GroupResult", b =>
                {
                    b.Property<string>("Grupo")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("PrimeiroTeamId")
                        .HasColumnType("int");

                    b.Property<int>("SegundoTeamId")
                        .HasColumnType("int");

                    b.HasKey("Grupo");

                    b.HasIndex("PrimeiroTeamId");

                    b.HasIndex("SegundoTeamId");

                    b.ToTable("GroupResults");
                });

            modelBuilder.Entity("WorldCup.Domain.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHoraUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Encerrado")
                        .HasColumnType("bit");

                    b.Property<int>("Fase")
                        .HasColumnType("int");

                    b.Property<int?>("GolsMandante")
                        .HasColumnType("int");

                    b.Property<int?>("GolsVisitante")
                        .HasColumnType("int");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("DataHoraUtc");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("WorldCup.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("WorldCup.Domain.Entities.Prediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("GolsMandantePalpite")
                        .HasColumnType("int");

                    b.Property<int>("GolsVisitantePalpite")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("PontosObtidos")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("UserId", "MatchId")
                        .IsUnique();

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("WorldCup.Domain.Entities.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LockBetsAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PontosArtilheiro")
                        .HasColumnType("int");

                    b.Property<int>("PontosCampeao")
                        .HasColumnType("int");

                    b.Property<int>("PontosClassificacaoPorAcerto")
                        .HasColumnType("int");

                    b.Property<int>("PontosMelhorJogador")
                        .HasColumnType("int");

                    b.Property<int>("PontosPlacarExato")
                        .HasColumnType("int");

                    b.Property<int>("PontosResultado")
                        .HasColumnType("int");

                    b.Property<string>("RegraDesempate")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("WorldCup.Domain.Entities.SpecialBet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArtilheiroPlayerId")
                        .HasColumnType("int");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("bit");

                    b.Property<int?>("CampeaoTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MelhorJogadorPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PontosObtidos")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtilheiroPlayerId");

                    b.HasIndex("CampeaoTeamId");

                    b.HasIndex("MelhorJogadorPlayerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SpecialBets");
                });

            modelBuilder.Entity("WorldCup.Domain.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoBandeira")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FifaCode")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Grupo");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("WorldCup.Domain.Entities.TournamentResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArtilheiroPlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("CampeaoTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("MelhorJogadorPlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtilheiroPlayerId");

                    b.HasIndex("CampeaoTeamId");

                    b.HasIndex("MelhorJogadorPlayerId");

                    b.ToTable("TournamentResults");
                });

            modelBuilder.Entity("WorldCup.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("Pago")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WorldCup.Domain.Entities.GroupQualifierBet", b =>
                {
                    b.HasOne("WorldCup.Domain.Entities.Team", "PrimeiroTeam")
                        .WithMany()
                        .HasForeignKey("PrimeiroTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorldCup.Domain.Entities.Team", "SegundoTeam")
                        .WithMany()
                        .HasForeignKey("SegundoTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorldCup.Domain.Entities.User", "User")
                        .WithMany("GroupQualifierBets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimeiroTeam");

                    b.Navigation("SegundoTeam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorldCup.Domain.Entities.GroupResult", b =>
                {
                    b.HasOne("WorldCup.Domain.Entities.Team", "PrimeiroTeam")
                        .WithMany()
                        .HasForeignKey("PrimeiroTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorldCup.Domain.Entities.Team", "SegundoTeam")
                        .WithMany()
                        .HasForeignKey("SegundoTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PrimeiroTeam");

                    b.Navigation("SegundoTeam");
                });

            modelBuilder.Entity("WorldCup.Domain.Entities.Match", b =>
                {
                    b.HasOne("WorldCup.Domain.Entities.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorldCup.Domain.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("WorldCup.Domain.Entities.Player", b =>
                {
                    b.HasOne("WorldCup.Domain.Entities.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WorldCup.Domain.Entities.Prediction", b =>
                {
                    b.HasOne("WorldCup.Domain.Entities.Match", "Match")
                        .WithMany("Predictions")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldCup.Domain.Entities.User", "User")
                        .WithMany("Predictions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorldCup.Domain.Entities.SpecialBet", b =>
                {
                    b.HasOne("WorldCup.Domain.Entities.Player", "ArtilheiroPlayer")
                        .WithMany()
                        .HasForeignKey("ArtilheiroPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorldCup.Domain.Entities.Team", "CampeaoTeam")
                        .WithMany()
                        .HasForeignKey("CampeaoTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorldCup.Domain.Entities.Player", "MelhorJogadorPlayer")
                        .WithMany()
                        .HasForeignKey("MelhorJogadorPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorldCup.Domain.Entities.User", "User")
                        .WithOne("SpecialBet")
                        .HasForeignKey("WorldCup.Domain.Entities.SpecialBet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtilheiroPlayer");

                    b.Navigation("CampeaoTeam");

                    b.Navigation("MelhorJogadorPlayer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorldCup.Domain.Entities.TournamentResult", b =>
                {
                    b.HasOne("WorldCup.Domain.Entities.Player", "ArtilheiroPlayer")
                        .WithMany()
                        .HasForeignKey("ArtilheiroPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorldCup.Domain.Entities.Team", "CampeaoTeam")
                        .WithMany()
                        .HasForeignKey("CampeaoTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WorldCup.Domain.Entities.Player", "MelhorJogadorPlayer")
                        .WithMany()
                        .HasForeignKey("MelhorJogadorPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ArtilheiroPlayer");

                    b.Navigation("CampeaoTeam");

                    b.Navigation("MelhorJogadorPlayer");
                });

            modelBuilder.Entity("WorldCup.Domain.Entities.Match", b =>
                {
                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("WorldCup.Domain.Entities.Team", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("WorldCup.Domain.Entities.User", b =>
                {
                    b.Navigation("GroupQualifierBets");

                    b.Navigation("Predictions");

                    b.Navigation("SpecialBet");
                });
#pragma warning restore 612, 618
        }
    }
}
